{{--
    Shared chrome for equipment PDF reports.
    Visual style matches resources/views/reports/submission-sheet-pdf.blade.php.

    Required vars:
      - $event           App\Models\Event
      - $report_title    string  e.g. "Delivery Checklist"
      - $generated_at    Carbon  injected by controller
    Optional sections:
      - @section('content')   main report body
--}}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{{ $event->name }} — {{ $report_title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #1e293b;
            background: #fff;
            line-height: 1.35;
        }

        @page { margin: 56px 36px 88px; }

        .header-bar {
            background-color: #1e3ea8;
            color: #fff;
            padding: 12px 12px 8px;
            margin-bottom: 12px;
            text-align: center;
        }
        .header-club {
            font-size: 11px; text-transform: uppercase; letter-spacing: .15em;
            color: #bfcfef; margin-bottom: 2px;
        }
        .header-event {
            font-size: 22px; font-weight: bold; letter-spacing: .04em;
            line-height: 1.1;
        }
        .header-sub { font-size: 12px; margin-top: 3px; color: #bfcfef; }
        .header-meta { font-size: 9px; margin-top: 3px; color: #bfcfef; letter-spacing: .04em; }

        .section { margin: 0 12px 10px; }
        .section-title {
            font-size: 9px; font-weight: bold; text-transform: uppercase;
            letter-spacing: .1em; color: #64748b;
            border-bottom: 2px solid #1e3ea8; padding-bottom: 2px; margin-bottom: 6px;
        }
        .section-note {
            font-weight: normal; text-transform: none; letter-spacing: normal;
            font-style: italic; color: #94a3b8;
        }

        table { width: 100%; border-collapse: collapse; font-size: 10px; }
        thead { display: table-header-group; }
        tr { page-break-inside: avoid; }

        th {
            background: #f1f5f9; color: #475569; font-weight: bold;
            text-transform: uppercase; letter-spacing: .05em; font-size: 8px;
            padding: 4px 6px; border: 1px solid #cbd5e1; text-align: left;
        }
        th.r { text-align: right; }
        th.c { text-align: center; }

        td { padding: 3px 6px; border: 1px solid #e2e8f0; vertical-align: middle; }
        td.r { text-align: right; font-family: DejaVu Sans Mono, monospace; }
        td.c { text-align: center; }
        td.m { font-family: DejaVu Sans Mono, monospace; font-weight: bold; }
        td.val { font-family: DejaVu Sans Mono, monospace; font-weight: bold; font-size: 12px; }

        tr.alt td { background: #f8fafc; }

        .check-box { font-size: 14px; color: #94a3b8; }
        .signature-line { display: inline-block; min-width: 140px; border-bottom: 1px solid #94a3b8; }
        .muted { color: #94a3b8; font-style: italic; }

        .summary-grid { width: 100%; margin-bottom: 6px; }
        .summary-grid td { background: #f0f4ff; border: 1px solid #cbd5e1; }
        .summary-label { font-size: 8px; text-transform: uppercase; letter-spacing: .05em; color: #64748b; }
        .summary-value { font-family: DejaVu Sans Mono, monospace; font-weight: bold; font-size: 14px; color: #1e3ea8; }

        .page-footer {
            position: fixed; bottom: 24px; left: 0; right: 0;
            border-top: 2px solid #1e3ea8; background: #fff;
        }
        .page-footer table { width: 100%; border-collapse: collapse; }
        .page-footer td {
            padding: 4px 12px; font-size: 9px; color: #475569;
            border: none;
        }
        .page-footer td.right { text-align: right; }
        .page-current:before { content: counter(page); }
        .page-break { page-break-before: always; }
    </style>
</head>
<body>

    <div class="page-footer">
        <table>
            <tbody>
                <tr>
                    <td>Generated by Field Day Commander &mdash; {{ $generated_at->format('Y-m-d H:i:s') }} UTC</td>
                    <td class="right">{{ $event->name }} &mdash; {{ $report_title }} &nbsp;&middot;&nbsp; Page <span class="page-current"></span></td>
                </tr>
            </tbody>
        </table>
    </div>

    @php($club_name = $event->eventConfiguration?->club_name)
    <div class="header-bar">
        @if ($club_name)
            <div class="header-club">{{ $club_name }}</div>
        @endif
        <div class="header-event">{{ $event->name }}</div>
        <div class="header-sub">{{ $report_title }}</div>
        <div class="header-meta">
            @if ($event->start_time && $event->end_time)
                {{ $event->start_time->format('M j') }} – {{ $event->end_time->format('M j, Y') }}
            @endif
        </div>
    </div>

    @yield('content')

</body>
</html>
