<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{{ $callsign }} — ARRL Field Day Submission Sheet</title>
    <style>
        /* -------------------------------------------------------
           Base — dompdf CSS2 subset, DejaVu for Unicode
        ------------------------------------------------------- */
        * { margin: 0; padding: 0; box-sizing: border-box; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 10px;
            color: #1e293b;
            background: #fff;
            line-height: 1.35;
        }

        @page { margin: 48px 0; }

        .header-bar {
            background-color: #1e3ea8;
            color: #fff;
            padding: 12px 48px 8px;
            margin-bottom: 12px;
        }
        .header-callsign {
            font-size: 26px; font-weight: bold; letter-spacing: .12em;
            text-transform: uppercase; font-family: DejaVu Sans Mono, monospace; line-height: 1.1;
        }
        .header-sub { font-size: 12px; margin-top: 3px; color: #bfcfef; }
        .header-meta { font-size: 9px; margin-top: 3px; color: #bfcfef; letter-spacing: .04em; }

        .section { margin: 0 48px 10px; }
        .section-title {
            font-size: 9px; font-weight: bold; text-transform: uppercase;
            letter-spacing: .1em; color: #64748b;
            border-bottom: 2px solid #1e3ea8; padding-bottom: 2px; margin-bottom: 6px;
        }
        .section-note {
            font-weight: normal; text-transform: none; letter-spacing: normal;
            font-style: italic; color: #94a3b8;
        }

        /* Tables ------------------------------------------------ */
        table { width: 100%; border-collapse: collapse; font-size: 10px; }

        th {
            background: #f1f5f9; color: #475569; font-weight: bold;
            text-transform: uppercase; letter-spacing: .05em; font-size: 8px;
            padding: 4px 6px; border: 1px solid #cbd5e1; text-align: left;
        }
        th.r  { text-align: right; }
        th.c  { text-align: center; }

        td { padding: 3px 6px; border: 1px solid #e2e8f0; vertical-align: middle; }
        td.r  { text-align: right; font-family: DejaVu Sans Mono, monospace; }
        td.c  { text-align: center; }
        td.m  { font-family: DejaVu Sans Mono, monospace; font-weight: bold; }
        td.val { font-family: DejaVu Sans Mono, monospace; font-weight: bold; font-size: 12px; }

        tr.alt td { background: #f8fafc; }
        .y  { color: #16a34a; font-weight: bold; }
        .n  { color: #cbd5e1; }

        .op-list { font-family: DejaVu Sans Mono, monospace; font-size: 10px; line-height: 1.5; }

        /* Footer ------------------------------------------------ */
        .page-footer {
            position: fixed; bottom: 24px; left: 0; right: 0;
            border-top: 2px solid #1e3ea8; background: #fff;
        }
        .page-footer table { width: 100%; border-collapse: collapse; }
        .page-footer td {
            padding: 4px 48px; font-size: 9px; color: #475569;
            border: none;
        }
        .page-footer td.right { text-align: right; }
        .page-current:before { content: counter(page); }
        .page-break { page-break-before: always; }
    </style>
</head>
<body>

    <div class="page-footer">
        <table>
            <tbody><tr>
                <td>Generated by Field Day Commander &mdash; {{ $generated_at->format('Y-m-d H:i:s') }} UTC</td>
                <td class="right">{{ $callsign }} &mdash; ARRL Field Day {{ $event_year }} &nbsp;&middot;&nbsp; Page <span class="page-current"></span> of {{ $total_pages }}</td>
            </tr></tbody>
        </table>
    </div>

    {{-- ============================================================
         HEADER
    ============================================================ --}}
    <div class="header-bar">
        <div class="header-callsign">{{ $callsign }}</div>
        <div class="header-sub">ARRL Field Day {{ $event_year }} — Submission Sheet</div>
        <div class="header-meta">
            field-day.arrl.org/fdentry.php ·
            {{ $event_start->format('M j') }} – {{ $event_end->format('M j, Y') }}
        </div>
    </div>

    {{-- ============================================================
         ENTRY INFO — mirrors top of ARRL form
         Call Used · GOTA Call · Section · Club Name
         Participants · Transmitters · Entry Class · Operators (B only)
    ============================================================ --}}
    <div class="section">
        <div class="section-title">Entry Information</div>
        <table>
            <tr>
                <th>Call Used</th>
                <th>GOTA Station Call</th>
                <th>ARRL/RAC Section</th>
                <th>Club or Group Name</th>
            </tr>
            <tr>
                <td class="val">{{ $callsign }}</td>
                <td class="val">{{ $gota_callsign ?: '—' }}</td>
                <td class="val">{{ $section }} <span style="font-size: 9px; font-weight: normal; color: #64748b;">{{ $section_name }}</span></td>
                <td class="m">{{ $club_name ?: '—' }}</td>
            </tr>
        </table>
        <table style="margin-top: 4px;">
            <tr>
                <th>Participants</th>
                <th>Transmitters</th>
                <th>Entry Class</th>
                <th>Power Multiplier</th>
            </tr>
            <tr>
                <td class="val">{{ $participant_count }}</td>
                <td class="val">{{ $transmitter_count }}</td>
                <td class="val">{{ $entry_class }}</td>
                <td class="val">{{ $power_multiplier }}×</td>
            </tr>
        </table>
    </div>

    {{-- ============================================================
         POWER SOURCE — matches ARRL checkbox order
    ============================================================ --}}
    <div class="section">
        <div class="section-title">Power Source <span class="section-note">check all that apply</span></div>
        <table>
            <tr>
                <th class="c">Generator</th>
                <th class="c">Commercial Mains</th>
                <th class="c">Battery</th>
                <th class="c">Solar</th>
                <th class="c">Other</th>
            </tr>
            <tr>
                <td class="c">{!! $uses_generator         ? '<span class="y">&#x2713;</span>' : '<span class="n">—</span>' !!}</td>
                <td class="c">{!! $uses_commercial_power  ? '<span class="y">&#x2713;</span>' : '<span class="n">—</span>' !!}</td>
                <td class="c">{!! $uses_battery           ? '<span class="y">&#x2713;</span>' : '<span class="n">—</span>' !!}</td>
                <td class="c">{!! $uses_solar             ? '<span class="y">&#x2713;</span>' : '<span class="n">—</span>' !!}</td>
                <td class="c">{!! $uses_other_power       ? '<span class="y">&#x2713;</span>' : '<span class="n">—</span>' !!}</td>
            </tr>
        </table>
    </div>

    {{-- ============================================================
         OPERATOR LIST — Class B only (ARRL form field)
    ============================================================ --}}
    @if ($operating_class_code === 'B' && ! empty($operators))
        <div class="section">
            <div class="section-title">List of Operators <span class="section-note">Class B</span></div>
            <div class="op-list">{{ implode(', ', $operators) }}</div>
        </div>
    @endif

    {{-- ============================================================
         BONUS POINTS — full ARRL checklist in form order
    ============================================================ --}}
    <div class="section">
        <div class="section-title">Bonus Points Claimed</div>
        <table>
            <tr>
                <th style="width: 50%;"></th>
                <th class="r">Points</th>
                <th class="c">Status</th>
            </tr>
            @foreach ($bonus_checklist as $i => $item)
                @if ($item['claimed'])
                    <tr class="{{ $i % 2 === 1 ? 'alt' : '' }}">
                        <td>{!! '<span class="y">&#x2713;</span>' !!} {{ $item['name'] }}@if ($item['auto']) <span style="font-size: 7px; color: #94a3b8;">(auto)</span>@endif</td>
                        <td class="r" style="font-weight: bold;">+{{ number_format($item['points']) }}</td>
                        <td class="c" style="font-size: 8px;">
                            @if ($item['is_verified'])
                                <span class="y">Verified</span>
                            @else
                                <span style="color: #b45309; font-weight: bold;">Claimed</span>
                            @endif
                        </td>
                    </tr>
                @else
                    <tr class="{{ $i % 2 === 1 ? 'alt' : '' }}" style="color: #cbd5e1;">
                        <td style="color: #cbd5e1;">{!! '<span class="n">&#x2717;</span>' !!} {{ $item['name'] }}@if ($item['auto']) <span style="font-size: 7px;">(auto)</span>@endif</td>
                        <td class="r" style="color: #cbd5e1;">—</td>
                        <td></td>
                    </tr>
                @endif
            @endforeach
        </table>
    </div>

    {{-- ============================================================
         CLAIMED SCORE — plain bordered table (dompdf-safe)
    ============================================================ --}}
    <div class="section">
        <div class="section-title">Claimed Score</div>
        <table style="background: #f0f4ff;">
            <tr>
                <th class="r">QSO Points</th>
                <th class="c">×</th>
                <th class="r">Power Multi.</th>
                <th class="c">=</th>
                <th class="r">QSO Score</th>
                <th class="c">+</th>
                <th class="r">Bonus Pts</th>
                @if ($has_gota_station)
                    <th class="c">+</th>
                    <th class="r">GOTA Bonus</th>
                @endif
                <th class="c">=</th>
                <th class="r">Total Score</th>
            </tr>
            <tr>
                <td class="r m" style="font-size: 13px; color: #1e3ea8;">{{ number_format($qso_base_points) }}</td>
                <td class="c" style="color: #64748b; font-size: 13px;">×</td>
                <td class="r m" style="font-size: 13px; color: #1e3ea8;">{{ $power_multiplier }}×</td>
                <td class="c" style="color: #64748b; font-size: 13px;">=</td>
                <td class="r m" style="font-size: 13px; color: #1e3ea8;">{{ number_format($qso_score) }}</td>
                <td class="c" style="color: #64748b; font-size: 13px;">+</td>
                <td class="r m" style="font-size: 13px; color: #1e3ea8;">{{ number_format($bonus_score) }}</td>
                @if ($has_gota_station)
                    <td class="c" style="color: #64748b; font-size: 13px;">+</td>
                    <td class="r m" style="font-size: 13px; color: #1e3ea8;">{{ number_format($gota_bonus + $gota_coach_bonus) }}</td>
                @endif
                <td class="c" style="color: #64748b; font-size: 13px;">=</td>
                <td class="r m" style="font-size: 16px; color: #1e3ea8;">{{ number_format($final_score) }}</td>
            </tr>
        </table>
    </div>

    {{-- ============================================================
         BAND/MODE QSO BREAKDOWN — own page, exact ARRL form layout
         CW QSOs/Pwr · Digital QSOs/Pwr · Phone QSOs/Pwr
         Bands: 160m 80m 40m 20m 15m 10m 6m 2m 222 432 Other Satellite
         Excludes GOTA QSOs.
    ============================================================ --}}
    <div class="page-break"></div>

    <div class="header-bar">
        <div class="header-callsign">{{ $callsign }}</div>
        <div class="header-sub">ARRL Field Day {{ $event_year }} — Band/Mode QSO Breakdown</div>
    </div>

    <div class="section">
        <div class="section-title">Band/Mode QSO Breakdown <span class="section-note">do not list GOTA QSOs</span></div>
        @php
            $cats = ['CW', 'Digital', 'Phone'];
            $catModeId = [];
            foreach ($modes as $mode) { $catModeId[$mode->category] = $mode->id; }
        @endphp
        <table style="font-size: 9px;">
            <thead>
                <tr>
                    <th scope="col" rowspan="2" style="vertical-align: bottom;">Band</th>
                    @foreach ($cats as $cat)
                        <th scope="col" class="c" colspan="2" style="border-bottom: none;">{{ $cat }}</th>
                    @endforeach
                </tr>
                <tr>
                    @foreach ($cats as $cat)
                        <th scope="col" class="r" style="font-size: 7px; border-top: none;">QSOs</th>
                        <th scope="col" class="r" style="font-size: 7px; border-top: none;">Pwr(W)</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @php $catTotals = array_fill_keys($cats, 0); @endphp
                @foreach ($bands as $i => $band)
                    @php
                        $rowTotal = 0; $rowCells = [];
                        foreach ($cats as $cat) {
                            $mid = $catModeId[$cat] ?? null;
                            $cell = $mid ? ($band_mode_grid[$mid][$band['id']] ?? ['qsos' => 0, 'power' => 0]) : ['qsos' => 0, 'power' => 0];
                            $rowCells[$cat] = $cell;
                            $rowTotal += $cell['qsos'];
                            $catTotals[$cat] += $cell['qsos'];
                        }
                    @endphp
                    <tr class="{{ $i % 2 === 1 ? 'alt' : '' }}">
                        <td class="m">{{ $band['name'] }}</td>
                        @foreach ($cats as $cat)
                            <td class="r">{{ $rowCells[$cat]['qsos'] ?: '' }}</td>
                            <td class="r">{{ $rowCells[$cat]['power'] ?: '' }}</td>
                        @endforeach
                    </tr>
                @endforeach
                <tr>
                    <td class="m" style="border-top: 2px solid #1e3ea8;">Total</td>
                    @foreach ($cats as $cat)
                        <td class="r" style="font-weight: bold; border-top: 2px solid #1e3ea8;">{{ $catTotals[$cat] ?: '' }}</td>
                        <td style="border-top: 2px solid #1e3ea8;"></td>
                    @endforeach
                </tr>
            </tbody>
        </table>
    </div>

    {{-- ============================================================
         GOTA BONUS — own page, exact ARRL form layout
         Name · Call · CW QSOs/Pwr · Digital QSOs/Pwr · Phone QSOs/Pwr
         Plus coach bonus checkbox
    ============================================================ --}}
    @if ($has_gota_station)
        <div class="page-break"></div>

        <div class="header-bar">
            <div class="header-callsign">{{ $callsign }}</div>
            <div class="header-sub">ARRL Field Day {{ $event_year }} — GOTA Bonus</div>
        </div>

        <div class="section">
            <div class="section-title">
                GOTA Bonus
                @if ($gota_coach_bonus > 0)
                    {!! '&nbsp; <span class="y" style="font-size: 8px; text-transform: none; letter-spacing: normal;">&#x2713; Coach bonus (+100)</span>' !!}
                @endif
            </div>
            <table style="margin-bottom: 4px;">
                <tr>
                    <th>GOTA Station Call</th>
                    <th class="r">Total GOTA QSOs</th>
                    <th class="r">Bonus Points</th>
                </tr>
                <tr>
                    <td class="val">{{ $gota_callsign ?: '—' }}</td>
                    <td class="r" style="font-weight: bold;">{{ $gota_contact_count }}</td>
                    <td class="r" style="font-weight: bold;">{{ number_format($gota_bonus + $gota_coach_bonus) }}</td>
                </tr>
            </table>

            <table style="font-size: 9px;">
                <thead>
                    <tr>
                        <th scope="col" rowspan="2" style="vertical-align: bottom;">Name</th>
                        <th scope="col" rowspan="2" style="vertical-align: bottom;">Call</th>
                        @foreach ($cats as $cat)
                            <th scope="col" class="c" colspan="2" style="border-bottom: none;">{{ $cat }}</th>
                        @endforeach
                    </tr>
                    <tr>
                        @foreach ($cats as $cat)
                            <th scope="col" class="r" style="font-size: 7px; border-top: none;">QSOs</th>
                            <th scope="col" class="r" style="font-size: 7px; border-top: none;">Pwr(W)</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @if (! empty($gota_operators))
                        @foreach ($gota_operators as $i => $op)
                            <tr class="{{ $i % 2 === 1 ? 'alt' : '' }}">
                                <td>{{ $op['name'] }}</td>
                                <td class="m">{{ $op['callsign'] ?: '—' }}</td>
                                @foreach ($cats as $cat)
                                    <td class="r">{{ ($op['modes'][$cat]['qsos'] ?? 0) ?: '' }}</td>
                                    <td class="r">{{ ($op['modes'][$cat]['power'] ?? 0) ?: '' }}</td>
                                @endforeach
                            </tr>
                        @endforeach
                    @else
                        <tr><td colspan="8" class="c" style="color: #94a3b8; font-style: italic;">No GOTA operators logged</td></tr>
                    @endif
                </tbody>
            </table>
        </div>
    @endif


</body>
</html>
